/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:a1fa2f004046fd9580e691133947e000:ac7608d1f04ab193bff21724566c15eb:e3a22faee007f1fda73a34184e7d7615$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class CapGuyDemo
	{
		public const string Background = "Background";
		public const string Capguy_turn_0001 = "capguy/turn/0001";
		public const string Capguy_turn_0002 = "capguy/turn/0002";
		public const string Capguy_turn_0003 = "capguy/turn/0003";
		public const string Capguy_turn_0004 = "capguy/turn/0004";
		public const string Capguy_turn_0005 = "capguy/turn/0005";
		public const string Capguy_turn_0006 = "capguy/turn/0006";
		public const string Capguy_turn_0007 = "capguy/turn/0007";
		public const string Capguy_turn_0008 = "capguy/turn/0008";
		public const string Capguy_turn_0009 = "capguy/turn/0009";
		public const string Capguy_turn_0010 = "capguy/turn/0010";
		public const string Capguy_turn_0011 = "capguy/turn/0011";
		public const string Capguy_turn_0012 = "capguy/turn/0012";
		public const string Capguy_walk_0001 = "capguy/walk/0001";
		public const string Capguy_walk_0002 = "capguy/walk/0002";
		public const string Capguy_walk_0003 = "capguy/walk/0003";
		public const string Capguy_walk_0004 = "capguy/walk/0004";
		public const string Capguy_walk_0005 = "capguy/walk/0005";
		public const string Capguy_walk_0006 = "capguy/walk/0006";
		public const string Capguy_walk_0007 = "capguy/walk/0007";
		public const string Capguy_walk_0008 = "capguy/walk/0008";
		public const string Capguy_walk_0009 = "capguy/walk/0009";
		public const string Capguy_walk_0010 = "capguy/walk/0010";
		public const string Capguy_walk_0011 = "capguy/walk/0011";
		public const string Capguy_walk_0012 = "capguy/walk/0012";
		public const string Capguy_walk_0013 = "capguy/walk/0013";
		public const string Capguy_walk_0014 = "capguy/walk/0014";
		public const string Capguy_walk_0015 = "capguy/walk/0015";
		public const string Capguy_walk_0016 = "capguy/walk/0016";
	}
}